# api_id and api_hash can be obtained from https://my.telegram.org
# bot_token can be obtained from https://t.me/botfather
# session_string can be obtained from https://repl.it/@subinps/GenerateStringSession
# sudo_users can be obtained from https://t.me/userinfobot

[pyrogram]
api_id =                                                       # required
api_hash = ""                       # required
bot_token = ""                  # either bot_token or session_string is required
session_string = "" # either bot_token or session_string is required
sudo_users = []                                 # optional


# chat ids can be obtained from https://t.me/getidsbot
# All chats must be in the format of [-]1001234567890
# You can add multiple chats in the format of a list
# You can also add multiple chats in the format of a list of lists
# Atleast one chat must be added

[[chats]]
from =         # required
to =               # required
replace = { "🐋   📣Some codes may be incorrect❗️" = "Change hoiche" } # optional

[[chats]]
from = [-1001610472708]               # required
to = -4510674591                                  # required
replace = { "only_apply_to_this_chat" = "new" } # optional

[[chats]]
from = -1001610472708            # required
to = [-4510674591] # required

[[chats]]
from = [-1001610472708] # required
to = [-4510674591]   # required
